environments:
  - name: Dev
    provisioner: gcp
    iacPolicy: "CC default latest"
    iacRoot: "terraform/dev"

pipelines:
  skaffold-deploy:
    - pipeline-config@1
    - git-clone@1
    - gke-skaffold@1

applications:
  msdemo:
    displayName: "Online Boutique"
    srcRoot: "."
    pipeline: skaffold-deploy

deployments:
  dev:
    endpoints:
      - msdemo
    environment:
      name: Dev
      inputs:
        gke_name: msdemo_online_boutique
    applications:
      msdemo:
        pipelineInputs:
          git_remote_path: github.com/vizkid/microservices-demo
          gke_cluster_name: "$$CLUSTER_NAME"
          gke_cluster_region: "$$GOOGLE_REGION"
          pipeline_env: '{"CLUSTER_NAME":"${terraform.gke.value.name}"}'
          pipeline_timeout_sec: "4000"
          pipeline_machine_type: "N1_HIGHCPU_32"
          pipeline_disk_size_gb: "300"
    output:
      frontend-endpoint:
        command: sleep 60; kubectl get --no-headers -o custom-columns=EXTERNAL-IP:.status.loadBalancer.ingress[0].ip service frontend-external

